// Auto-generated by pre-build script. Do not edit manually.
enum GitVersion {
    static let commitHash = "unknown"
    static let isDirty = false

    static var isAvailable: Bool {
        commitHash != "unknown" && !commitHash.isEmpty
    }

    static var displayVersion: String {
        guard isAvailable else { return "unknown" }
        return isDirty ? "\(commitHash)-dirty" : commitHash
    }
}
