// Auto-generated by pre-build script. Do not edit manually.
enum GitVersion {
    static let commitHash = "48ed10b"
    static let isDirty = false
    static let marketingVersion = "1.0.1"
    static var isAvailable: Bool {
        commitHash != "unknown" && !commitHash.isEmpty
    }
    static var displayVersion: String {
        guard isAvailable else { return "unknown" }
        return isDirty ? "\(commitHash)-dirty" : commitHash
    }
}
